version: "3.9"

services:
  web:
    build: .
    container_name: smart_energy_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./model:/app/model
    restart: unless-stopped
